version: '2'
services:
  slackin:
    image: codeformuenster/slackin:0.8.3
    env_file:
      - ./secrets/slack-token.env
    environment:
      - SLACK_ORG=c4m

networks:
  default:
    external:
      name: caddy
