# docker run -p 9090:9090 -v /prometheus-data \
#   prom/prometheus -config.file=/prometheus-data/prometheus.yml

version: '2'
services:
  prometheus:
    image: prom/prometheus:0.20.0
    volumes:
      - ./conf:/etc/prometheus
      - ./data:/prometheus
