version: '2'
services:
  grafana:
    image: grafana/grafana:3.1.0
    env_file:
      - ./secrets/admin-password.env
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.codeformuenster.org
    volumes:
      - ./conf:/etc/grafana
      - ./data:/var/lib/grafana

networks:
  default:
    external:
      name: caddy
