version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.0
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      # ES_JAVA_OPTS: "-Des.path.conf=/etc/elasticsearch"
      # CMD ["-E", "network.host=0.0.0.0", "-E", "discovery.zen.minimum_master_nodes=1"]
    volumes:
      - ./conf:/etc/elasticsearch
      - ./data:/usr/share/elasticsearch/data

networks:
  default:
    external:
      name: caddy

# You need to increase max_map_count on your Docker host:
# $ sysctl -w vm.max_map_count=262144
