
global:
  scrape_interval: 10s
  evaluation_interval: 10s
    #^ for rule_files

  external_labels:
    monitor: 'codeformuenster'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus-node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
