version: '2'
services:
  json-server:
    image: dockermuenster/json-server:0.8.15
    volumes:
     - ./conf:/etc/json-server
     - ./data:/var/lib/json-server

networks:
  default:
    external:
      name: caddy
